export type Slide = {
  id: number
  title: string
  act: string
  actNumber: number
  speaker: string
  component: string
  speakerNotes: string
  source: string
}

export const SLIDES: Slide[] = [
  { id: 1, title: 'External Strategic Analysis: Integrated Protection Services', act: 'ACT 1: THE WORLD YOU BUILT', actNumber: 1, speaker: 'AJ McKean', component: 'Slide01', speakerNotes: 'Opens the presentation. Sets the tone — this is not a class project, it is a strategic intelligence brief for real decisions. Introduce the team, the engagement scope, and the thesis in one sentence.', source: 'Xavier EMBA Capstone' },
  { id: 2, title: 'IPS Today: A Company That\'s Winning', act: 'ACT 1: THE WORLD YOU BUILT', actNumber: 1, speaker: 'AJ McKean', component: 'Slide02', speakerNotes: 'You\'ve built something rare. A $55M independent integrator growing at 20% organically in an industry where most companies your size sold to PE years ago. That\'s the foundation everything we\'re about to show you stands on.', source: 'IPS Leadership Meeting (March 20, 2026) · IPS VTO' },
  { id: 3, title: 'What Success Looks Like: The IPS Vision', act: 'ACT 1: THE WORLD YOU BUILT', actNumber: 1, speaker: 'AJ McKean', component: 'Slide03', speakerNotes: 'PIVOT POINT: Your targets are ambitious and achievable — IF the industry you\'re planning for is the same industry you\'ll be competing in. This is the transition. We\'re about to show them the industry is changing shape underneath their feet.', source: 'IPS VTO (March 20, 2026)' },
  { id: 4, title: 'Two Industries Becoming One', act: 'ACT 2: THE CONVERGENCE SQUEEZE', actNumber: 2, speaker: 'Katy Peat', component: 'Slide04', speakerNotes: 'When the fire alarm code itself requires cybersecurity compliance, fire and IT are no longer separate industries. You describe yourselves as 50% fire, 50% security. The market is reorganizing into something bigger.', source: 'Plunkett Research via Xavier/Gale · NFPA 72 (2025) · Team PESTEL Workbook' },
  { id: 5, title: '$12 Billion Is Pointed at Your Market', act: 'ACT 2: THE CONVERGENCE SQUEEZE', actNumber: 2, speaker: 'Katy Peat', component: 'Slide05', speakerNotes: 'Combined PE platform debt exceeds $9.6 billion. Pye-Barker alone has $680 million in undrawn capacity. Leonard Green controls both the #1 and #2 PE platforms — $3.7 billion in combined fire and security revenue. This isn\'t competition — it\'s an industry reorganization backed by the world\'s largest capital pools.', source: 'PitchBook · Capstone Partners Feb 2026 · SDM Magazine · BusinessWire' },
  { id: 6, title: 'The Convergence Timeline: Three Waves', act: 'ACT 2: THE CONVERGENCE SQUEEZE', actNumber: 2, speaker: 'Katy Peat', component: 'Slide06', speakerNotes: 'Fire is the last piece to converge — and that\'s why it\'s your most valuable asset. But last doesn\'t mean never. The fire alarm moat buys you 3-5 years. The question is what you do with that time.', source: 'Team PESTEL Workbook · Pete Keller Consultation (March 25, 2026) · NFPA 72 (2025)' },
  { id: 7, title: 'Strategic Group Map: 2025 vs. 2028', act: 'ACT 2: THE CONVERGENCE SQUEEZE', actNumber: 2, speaker: 'Kyu Hyuk Choi', component: 'Slide07', speakerNotes: 'IPS sits in the lower-right quadrant: full-service, regional focus. This is the most defensible position for an independent today. Hover any bubble to see company details. Toggle 2025/2028 to see projected movement.', source: 'PitchBook · Plunkett Research · IPS Leadership Meeting' },
  { id: 8, title: 'Strategic Group Map: 2028 (Projected Movement)', act: 'ACT 2: THE CONVERGENCE SQUEEZE', actNumber: 2, speaker: 'Kyu Hyuk Choi', component: 'Slide08', speakerNotes: 'Every IPS market now has at least one PE-backed competitor. The question isn\'t whether convergence reaches you — it\'s whether you\'re positioned to thrive in the converged industry.', source: 'PitchBook deal data · Capstone Partners · IPS VTO' },
  { id: 9, title: 'The Convergence Squeeze', act: 'ACT 2: THE CONVERGENCE SQUEEZE', actNumber: 2, speaker: 'Kyu Hyuk Choi', component: 'Slide09', speakerNotes: 'You\'re not losing today. But the ceiling is lowering and the floor is rising. The partner buyout makes this existential: grow revenue and RMR fast enough to fund it internally, or the PE offer becomes the only path. The window is 3-5 years.', source: 'IPS Leadership (Mar 2026) · PitchBook · Capstone Partners · MarketsandMarkets · Plunkett Research' },
  { id: 10, title: 'The Fire Alarm Moat: Your Offensive Weapon', act: 'ACT 3: YOUR MOAT AND YOUR GAPS', actNumber: 3, speaker: 'Zahria Tucker', component: 'Slide10', speakerNotes: 'Fire alarm isn\'t just your defense — it\'s your Trojan horse. Once you install fire, you own the customer relationship for everything else. Every inspection, test, and service call is a chance to sell managed security, monitoring, and cloud services.', source: 'IPS Leadership Meeting · Pete Keller · IPS Service Flyer' },
  { id: 11, title: 'The Gaps the Converged Industry Exposes', act: 'ACT 3: YOUR MOAT AND YOUR GAPS', actNumber: 3, speaker: 'Zahria Tucker', component: 'Slide11', speakerNotes: 'None of these gaps are fatal. But in the converged industry, the companies that fill these gaps first capture the recurring revenue pools that drive enterprise value.', source: 'IPS VTO (issues + weaknesses list) · Pete Keller Consultation (March 25, 2026)' },
  { id: 12, title: 'RMR: The Business Model of the Converged Industry', act: 'ACT 3: YOUR MOAT AND YOUR GAPS', actNumber: 3, speaker: 'Zahria Tucker', component: 'Slide12', speakerNotes: 'Pete told us — you know this drives enterprise value. The industry is making it easier: manufacturers are mandating subscription models, customers are expecting OpEx pricing, and your Brivo/Eagle Eye platform already supports it.', source: 'IPS Leadership Meetings · Pete Keller · Plunkett Research benchmarks' },
  { id: 13, title: 'What IPS Has — and What It\'s Missing', act: 'ACT 3: WHERE IPS STANDS', actNumber: 3, speaker: 'Zahria Tucker', component: 'Slide13', speakerNotes: 'IPS is world-class at the technical craft — NICET IV, fire+security under one roof, 25+ vendor partnerships. But the business systems that scale from $55M to $150M — recurring revenue, workforce pipeline, documented processes — are the gaps. The barbell: incredible at craft, underweight on the systems side.', source: 'IPS Leadership (Mar 2026) · IPS VTO · PitchBook · SDM Top 100 (2024)' },
  { id: 14, title: 'The Strategic Imperative', act: 'ACT 4: THE PATH FORWARD', actNumber: 4, speaker: 'Ryan Eger', component: 'Slide14', speakerNotes: 'IPS must grow fast enough to fund the buyout of a 42% partner — without surrendering independence to private equity. The converged industry model is simultaneously the threat AND the solution.', source: 'IPS Leadership Meeting (March 20, 2026) · IPS VTO' },
  { id: 15, title: 'Path 1: RMR Acceleration', act: 'ACT 4: THE PATH FORWARD', actNumber: 4, speaker: 'Ryan Eger', component: 'Slide15', speakerNotes: 'Start immediately. Highest leverage, lowest capital requirement. No new headcount needed to begin. Going sub-20% to 50%+ RMR takes the enterprise value multiplier from 3x to 6x+.', source: 'IPS Leadership Meetings · Plunkett Research · Capstone Partners' },
  { id: 16, title: 'Path 2: Geographic Expansion — Atlanta', act: 'ACT 4: THE PATH FORWARD', actNumber: 4, speaker: 'Ryan Eger', component: 'Slide16', speakerNotes: 'Leader-first model. The Nashville playbook is proven — fire = buy, security = greenfield. Existing customers are already requesting Atlanta coverage. Aligns with VTO 3-year target.', source: 'IPS Leadership Meeting · 2021 Xavier Study · IPS VTO' },
  { id: 17, title: 'Path 3: Capability Expansion', act: 'ACT 4: THE PATH FORWARD', actNumber: 4, speaker: 'Ryan Eger', component: 'Slide17', speakerNotes: 'You don\'t need to become Convergint. You need to become the independent alternative — the converged platform with local relationships, fast decisions, and the GAS factor that PE platforms lose after acquisition.', source: 'IPS Leadership Meeting · Pete Keller · VTO · Team competitor research' },
  { id: 18, title: 'The 2021 Study Got You Here. This Gets You There.', act: 'ACT 4: THE PATH FORWARD', actNumber: 4, speaker: 'Ryan Eger', component: 'Slide18', speakerNotes: 'The 2021 team asked the right question for 2021. The industry has changed. Geographic expansion is still necessary — but in 2026 it is necessary, not sufficient.', source: 'IPS Final Recommendation (Xavier EMBA, Dec 2021) · IPS Leadership Meeting (March 20, 2026)' },
  { id: 19, title: 'The Window: Use It', act: 'ACT 5: CLOSE', actNumber: 5, speaker: 'Ryan Eger', component: 'Slide19', speakerNotes: 'The fire alarm moat gives you 3-5 years where your competitive position is strong. That window aligns almost perfectly with the partner buyout timeline. Use it.', source: 'IPS VTO · IPS Leadership Meeting' },
  { id: 20, title: 'Summary: Three Paths, One Destination', act: 'ACT 5: CLOSE', actNumber: 5, speaker: 'Ryan Eger', component: 'Slide20', speakerNotes: 'Three paths. All interconnected. All serve the buyout timeline. The destination: an independent, converged building intelligence platform anchored by fire alarm expertise.', source: 'IPS Leadership Meeting · IPS VTO · Team Research' },
  { id: 21, title: 'What\'s Next', act: 'ACT 5: CLOSE', actNumber: 5, speaker: 'Ryan Eger', component: 'Slide21', speakerNotes: 'You told us to be contrary. We are. Not because you\'re doing something wrong — you\'re winning. But the industry is reorganizing, and the company that recognizes this first and acts on it will define the next era. We think that company should be IPS.', source: 'Xavier EMBA Capstone Team · May 8, 2026' },
  { id: 22, title: 'The Industry Landscape', act: 'ACT 1: THE WORLD YOU BUILT', actNumber: 1, speaker: 'AJ McKean', component: 'Slide22', speakerNotes: 'Two NAICS codes define IPS\'s world: 238210 (electrical contractors, $223.6B) and 561621 (security systems, $33.2B). Combined addressable market: $256 billion. 6,136 security firms nationally, average revenue $4.79M — IPS at $55M is top tier. Cloud/XaaS growing 16-18% CAGR while base market grows 4%.', source: 'Plunkett Research via Xavier/Gale (NAICS 561621, 238210) · SDM Magazine Top 100 (2024) · MarketsandMarkets · Grand View Research · IBISWorld' },
  { id: 23, title: 'The Demand Environment', act: 'ACT 1: THE PLAYING FIELD', actNumber: 1, speaker: 'AJ McKean', component: 'Slide23', speakerNotes: 'Thirteen of seventeen macro trends are favorable. Federal grants exceeding $1B. Columbus is #3 nationally in data center capacity with 77 facilities and 2.4 GW planned. Cloud/XaaS growing 3-4x faster than the base market. But the binding constraint is labor — 29% of fire workforce retiring by 2026, 52% of security firms report hiring difficulty, and no industry apprenticeship infrastructure exists at scale. Whoever solves workforce wins.', source: 'Team PESTEL Workbook · FEMA.gov · ConstructConnect · MarketsandMarkets · Genetec 2026 · BLS' },
  { id: 24, title: 'Four Things the External Environment Is Telling You', act: 'ACT 2: THE INDUSTRY IS CONVERGING', actNumber: 2, speaker: 'Ryan Eger', component: 'Slide24', speakerNotes: 'Your industry is becoming one market. Someone else is building what you could be. Fire is your most defensible asset. And RMR is the answer to almost every question. The partner buyout makes growth existential — the external environment frames the challenge, the internal analysis answers it.', source: 'IPS Leadership (Mar 2026) · PitchBook · Capstone Partners · Plunkett Research · NFPA 72 (2025) · SDM Magazine · MarketsandMarkets' },
  // === EXTERNAL UPDATE: EC CONSOLIDATION (Slides 25-30) ===
  { id: 25, title: 'The Third Consolidation Wave: Electrical Contractors', act: 'ACT 2: THE CONVERGENCE SQUEEZE', actNumber: 2, speaker: 'Ryan Eger', component: 'Slide25', speakerNotes: '$255B industry, 219K businesses, 79 deals in 2024 with 73% PE-driven. FMI says early innings. Data centers driving 45-70% of construction cost. Labor scarcity makes acquisition the fastest hiring mechanism.', source: 'BMI Mergers · FMI Capital Advisors · Capstone Partners · McKinsey data center estimates' },
  { id: 26, title: 'The Vertical Integration Thesis: Own the Door, Own the RMR', act: 'ACT 2: THE INDUSTRY IS CONVERGING', actNumber: 2, speaker: 'Ryan Eger', component: 'Slide26', speakerNotes: 'PE buys EC for building access. Layers fire and security in-house. Captures subcontractor margin AND recurring revenue tail. APi Group is the proof — from specialty contractor to $7.9B life safety platform. Every $1 inspection generates $3-4 annual service revenue.', source: 'APi Group SEC filings · ArchKey Solutions · EMCOR Group disclosures · Lincoln International' },
  { id: 27, title: 'Who Is Already Doing It', act: 'ACT 2: THE INDUSTRY IS CONVERGING', actNumber: 2, speaker: 'Ryan Eger', component: 'Slide27', speakerNotes: 'Seven platforms have fire+security inside an EC. EMCOR has hundreds of NICET staff. ArchKey has a dedicated national fire team and is hiring NICET estimators. IES Communications segment grew 56% YoY. This is not theoretical — these divisions are operational and competing for work today.', source: 'EMCOR SEC filings · ArchKey corporate website · IES Holdings SEC filings · Hunt Electric · Norlee/Heartwood press releases' },
  { id: 28, title: 'Updated Convergence Map: Three Fronts', act: 'ACT 2: THE INDUSTRY IS CONVERGING', actNumber: 2, speaker: 'Ryan Eger', component: 'Slide28', speakerNotes: 'Original analysis showed two fronts — PE platforms above, cloud disruptors below. EC consolidation adds the third front from inside the project pipeline. The three fronts reinforce each other. When PE buys an EC, it gains project access. When it adds fire/security, it gains RMR. The independent integrator is squeezed from all three directions.', source: 'Team analysis integrating PitchBook · BMI Mergers · Capstone Partners · Lincoln International' },
  { id: 29, title: 'Updated PE Capital Map: $12B+ Across All Three Fronts', act: 'ACT 2: THE INDUSTRY IS CONVERGING', actNumber: 2, speaker: 'Ryan Eger', component: 'Slide29', speakerNotes: 'Leonard Green owns majority stakes in BOTH Convergint and Pye-Barker — $3.7B combined. 26North owns ArchKey with integrated EC+fire+security. Apollo owns The State Group expanding fire/security across KY, IN, TN. Lone Star owns Edwards — controls the fire OEM supply. The ownership consolidation has already happened at the PE level.', source: 'PitchBook · company press releases · SEC filings' },
  { id: 30, title: 'The Question the External Environment Is Asking', act: 'ACT 2: THE INDUSTRY IS CONVERGING', actNumber: 2, speaker: 'Ryan Eger', component: 'Slide30', speakerNotes: 'One — your industry is becoming one market. Two — someone else is building what you could be. Three — fire is defensible but the door is being bought. Four — RMR is the answer and ECs are coming for it too. Five — the window is shorter than we thought. PE-driven M&A assembles fire capability in 90 days.', source: 'Synthesis of all external analysis frameworks plus EC consolidation research' },
  // === INTERNAL ANALYSIS: ACT 6 — WHAT THE NUMBERS SAY (Slides 31-34) ===
  { id: 31, title: 'Internal Analysis: What the Numbers Say', act: 'ACT 6: WHAT THE NUMBERS SAY', actNumber: 6, speaker: 'Ryan Eger', component: 'Slide31', speakerNotes: 'The external analysis established the forces. This internal analysis asks the harder question — does IPS have the financial and operational foundation to compete? The answer is nuanced. IPS is a healthy, growing business with genuinely rare technical capability. But underneath the growth story, operational metrics are deteriorating.', source: 'IPS Financial Model V3 · audited financial statements 2021-2025 · 30K invoice records · 43K vendor AP records' },
  { id: 32, title: 'Revenue Trajectory and Financial Position', act: 'ACT 6: WHAT THE NUMBERS SAY', actNumber: 6, speaker: 'Ryan Eger', component: 'Slide32', speakerNotes: 'Revenue: $28M to $54M in 3 years, all organic. Gross margin: 29.7% to 35.6%. Real improvement. But EBITDA margin declined from 11.4% to 10.7% despite gross margin gains. Revenue grew 26%. SGA grew 52%. Cash ended negative. The growth consumed the improvement.', source: 'IPS audited financials · IPS Financial Model V3' },
  { id: 33, title: 'The Glass House', act: 'ACT 6: WHAT THE NUMBERS SAY', actNumber: 6, speaker: 'Ryan Eger', component: 'Slide33', speakerNotes: 'IPS grew revenue 26% in 2025 and ended the year with negative cash. Eleven metrics tell the story. Revenue up — looks great. Gross margin up — looks great. EBITDA margin down. Cash negative. DSO spiked 22 days. Bad debt up 94x. SGA up 4.3 points. Top 3 concentration up to 46.4%. Backlog flat. RMR barely moved. The revenue growth is real but masking deterioration in almost every operational health metric.', source: 'IPS audited financials 2024-2025 · invoice analysis · VTO' },
  { id: 34, title: 'Revenue Composition: Where the Money Comes From', act: 'ACT 6: WHAT THE NUMBERS SAY', actNumber: 6, speaker: 'Ryan Eger', component: 'Slide34', speakerNotes: '78.5% project installation at 20-25% margin. 14% service break-fix at 45-50% margin. 5.8% recurring contracts at 50-60% margin. The highest-margin revenue is the smallest category. And the fastest-growing segment — fire through EC — is the lowest margin at 18% with zero RMR potential.', source: 'IPS Financial Model V3 · 3-year invoice analysis' },
  // === INTERNAL ANALYSIS: ACT 7 — WHERE IPS CREATES VALUE (Slides 35-39) ===
  { id: 35, title: 'VRIO Analysis: 12 Resources Assessed', act: 'ACT 7: WHERE IPS CREATES VALUE', actNumber: 7, speaker: 'Katy Peat', component: 'Slide35', speakerNotes: 'We assessed 12 resources across Valuable, Rare, Inimitable, and Organized. Four score as Unused Competitive Advantages — valuable and defensible but IPS is not organized to capture their full value. One scores as a Competitive Disadvantage: recurring revenue at 5.8%. The Organization gap is systemic — 6 of 12 resources fail on the O dimension.', source: 'VRIO scaffold analysis · IPS financial data · VTO · leadership interviews' },
  { id: 36, title: 'The Organization Gap', act: 'ACT 7: WHERE IPS CREATES VALUE', actNumber: 7, speaker: 'Katy Peat', component: 'Slide36', speakerNotes: 'NICET IV engineering, customer relationships, leadership knowledge, and regulatory expertise are all genuinely rare and defensible. But none are organized into systems. Knowledge is trapped in people, not codified in processes. No CRM, no training program, no succession plan, no subscription billing. The VTO identifies these gaps. 18 months of EOS has not closed them.', source: 'VTO · VRIO analysis · leadership meeting notes' },
  { id: 37, title: 'Channel Profitability: Where IPS Actually Makes Money', act: 'ACT 7: WHERE IPS CREATES VALUE', actNumber: 7, speaker: 'Katy Peat', component: 'Slide37', speakerNotes: 'EC subcontract is 43% of revenue but only 30% of gross profit — and generates zero recurring revenue. Service and recurring is 18% of revenue but 35% of gross profit — and IS the recurring revenue. IPS is growing fastest in its least profitable, least sticky channel. Fire through EC is 37% of total revenue at 18% margin.', source: '3-year invoice analysis (30,241 records) · margin estimates from leadership interviews' },
  { id: 38, title: 'Value Chain: Margin Creation vs Margin Leakage', act: 'ACT 7: WHERE IPS CREATES VALUE', actNumber: 7, speaker: 'Katy Peat', component: 'Slide38', speakerNotes: 'Margin creation: fire engineering, service agreements at 50% margin, PSA/Edwards purchasing leverage. Margin leakage: EC channel compression, post-installation handoff gap, 20% subcontractor spend, $11.8M in credit card purchasing, 122-day DSO tying up $18M in receivables.', source: '3-year vendor AP analysis (42,786 records) · invoice analysis · financial model' },
  { id: 39, title: 'The Handoff Gap', act: 'ACT 7: WHERE IPS CREATES VALUE', actNumber: 7, speaker: 'Katy Peat', component: 'Slide39', speakerNotes: 'Current model: Install, train, walk away, wait for service call. Ideal model: Install, convert to monitoring, add service agreement, layer managed services, annual inspections, technology refresh. Pete Keller described it himself — IPS installs, trains, and walks away. Customer self-manages. The building owner calls whoever shows up with a monthly invoice.', source: 'Pete Keller debrief March 25 2026 · value chain analysis · customer LTV model' },
  // === INTERNAL ANALYSIS: ACT 8 — THE GEOGRAPHY ENGINE (Slides 40-43) ===
  { id: 40, title: 'IPS Does Not Have a Growth Engine', act: 'ACT 8: THE GEOGRAPHY ENGINE', actNumber: 8, speaker: 'Zahria Tucker', component: 'Slide40', speakerNotes: 'IPS does not grow the customer book. It does not generate inbound leads. It does not run outbound campaigns. It does not convert installed customers into recurring subscribers. It farms existing relationships, executes projects, and when relationships churn at 18.5% per year, there is nothing behind them.', source: 'Invoice analysis · customer retention data · VTO growth strategy · leadership interviews' },
  { id: 41, title: 'The Treadmill', act: 'ACT 8: THE GEOGRAPHY ENGINE', actNumber: 8, speaker: 'Zahria Tucker', component: 'Slide41', speakerNotes: 'Cincinnati was the foundation. Columbus added growth. Lexington added a little. Nashville added more. National Accounts added $21M in one year — then lost $12M the next. The VTO says Atlanta next. Then branch 7. Then 8. $150M by 2034. Every market IPS would enter next already has PE-backed competition.', source: 'IPS revenue history · VTO 10-year plan · PE geographic analysis' },
  { id: 42, title: 'Customer Acquisition Reality', act: 'ACT 8: THE GEOGRAPHY ENGINE', actNumber: 8, speaker: 'Zahria Tucker', component: 'Slide42', speakerNotes: '207 new customers acquired in 2025. 185 lost. Net gain: 22. No outbound sales. No formal sales training. VTO says shift from farming to hunting — as a 2028 aspiration. Not a 2026 action.', source: 'Invoice analysis customer counts · VTO 3-year picture · leadership meeting notes' },
  { id: 43, title: 'Confirmed by Leadership', act: 'ACT 8: THE GEOGRAPHY ENGINE', actNumber: 8, speaker: 'Zahria Tucker', component: 'Slide43', speakerNotes: 'We tested every element of this thesis against what leadership told us March 20. Eight for eight confirmed. Andy calls RMR existential — VTO has zero RMR action items. VTO says shift from farming to hunting — as a 2028 aspiration. Leadership describes themselves as cash-positive — actual position is negative $71K. Andy asked us to be contrarian. This is it.', source: 'IPS Strategy Meeting March 20 2026 · Pete Keller Debrief March 25 2026' },
  // === INTERNAL ANALYSIS: ACT 9 — WHAT BREAKS (Slides 44-48) ===
  { id: 44, title: 'Model Pressure Test: 3 Hold, 5 Crack', act: 'ACT 9: WHAT BREAKS', actNumber: 9, speaker: 'Kyu Hyuk Choi', component: 'Slide44', speakerNotes: 'Three hold: revenue trajectory, total COGS decline, direct labor leverage. Five crack: COGS components distorted, DSO at 75 days structurally impossible, SGA at 21% contradicted by 2025, RMR never crosses 10% organically, $37M in acquisition costs missing from cash flow.', source: 'IPS Financial Model V3 pressure test against 30K invoices · 43K vendor AP records · audited financials' },
  { id: 45, title: 'Convergence Vulnerability Scorecard', act: 'ACT 9: WHAT BREAKS', actNumber: 9, speaker: 'Kyu Hyuk Choi', component: 'Slide45', speakerNotes: 'Fire installation through EC — $24.9M, largest segment — scores 1/5 on defensibility. Fire service and inspection — $3M — scores 5/5. The moat protects $3M. The other $25M is exposed. Fire the capability is defensible. Fire the revenue stream as structured is the most vulnerable revenue in the business.', source: 'Convergence vulnerability analysis · PE/EC consolidation intelligence · PitchBook data' },
  { id: 46, title: 'Scenario G: Full Vertical Displacement', act: 'ACT 9: WHAT BREAKS', actNumber: 9, speaker: 'Kyu Hyuk Choi', component: 'Slide46', speakerNotes: 'Revenue drops $31M by 2029. Percentage model shows margins improving. Fixed-cost model shows reality: 140 employees do not disappear. 2028-2029 is the valley of death — EBITDA compresses to $7.5-8.2M. By 2030 the remaining business is higher quality. But you have to survive the valley.', source: 'Financial model stress test · fixed cost analysis · invoice data channel breakdown' },
  { id: 47, title: 'Scenario H: The Cascading Failure', act: 'ACT 9: WHAT BREAKS', actNumber: 9, speaker: 'Kyu Hyuk Choi', component: 'Slide47', speakerNotes: 'Revenue declines. Partner demands exit at 72. IPS has $3.5M FCF — cannot fund $27M buyout at $4.6M/yr. Four outcomes, all bad. Negotiated: drains all cash. Peak price: impossible. Distressed sale: everyone loses 40%. PE buys partner stake: IPS loses control. The buyout costs the same in 2026 or 2028. FCF is 3x higher in 2026.', source: 'Partner buyout analysis · stress test FCF projections · PE minority acquisition playbook' },
  { id: 48, title: 'The Valuation Paradox', act: 'ACT 9: WHAT BREAKS', actNumber: 9, speaker: 'Kyu Hyuk Choi', component: 'Slide48', speakerNotes: '$92M company at 5.8% RMR at 1.0x = $92M EV. $61M company at 15-20% RMR at 1.5-2.0x = $92-122M EV. The smaller company could be worth more if the revenue that remains is higher quality. Losing the EC channel and Amazon might be the best thing that could happen — if it forces the pivot.', source: 'Valuation analysis · RMR multiple tiers from Breakwater M&A · scenario modeling' },
  // === INTERNAL ANALYSIS: ACT 10 — WHAT REPLACES IT (Slides 49-50) ===
  { id: 49, title: 'Three Recommendations', act: 'ACT 10: WHAT REPLACES IT', actNumber: 10, speaker: 'All', component: 'Slide49', speakerNotes: 'Not growth tactics — business model transformation. One: stop leaving the building. Make the monthly invoice part of every project close. Two: build or buy the delivery capability — NOC, helpdesk, subscription billing. Three: redesign sales compensation to reward recurring revenue. Until incentives change, behavior will not change.', source: 'Synthesis of all internal and external analysis' },
  { id: 50, title: 'The Order: Buyout First, Then Pivot, Then Build', act: 'ACT 10: WHAT REPLACES IT', actNumber: 10, speaker: 'All', component: 'Slide50', speakerNotes: 'Buyout while revenue is growing and FCF is strong — 2026-2027. The pivot causes the revenue mix shift that could trigger partner panic. Full control enables transformation. Leonard Green already owns Convergint and Pye-Barker. The operational coordination is one board meeting away. The clock is not 2-3 years. PE is already here.', source: 'Buyout timing analysis · PitchBook ownership data · Leonard Green dual platform ownership' },
  // === STRESS TEST: ACT 11 (Slides 51-53) ===
  { id: 51, title: 'Stress Testing the Thesis', act: 'ACT 11: STRESS TEST', actNumber: 11, speaker: 'All', component: 'Slide51', speakerNotes: 'We built this analysis to be disproved. Seven counter-arguments, each given the strongest possible case. Two are valid, four partially hold, one is invalidated. What survived the stress test is what belongs in front of leadership.', source: 'Internal Strategic Analysis Part I · IPS Financial Model V5 · All prior research' },
  { id: 52, title: 'Seven Counter-Arguments: The Verdict', act: 'ACT 11: STRESS TEST', actNumber: 11, speaker: 'All', component: 'Slide52', speakerNotes: 'The organic growth is real but the quality is poor. The NICET moat protects relevance not revenue. Retention metric is noisy but the gap is real. Cash is a distribution choice for one year but structural for five. PE competitors are messy in direct sales but that does not help the 43% flowing through EC. The base case works if the environment stays static — it will not. And Amazon is the worst: warehouse commodity work with no moat and MSA vulnerability.', source: 'Counter-argument stress test analysis · IPS Financial Model V5 scenarios' },
  { id: 53, title: 'What Survived', act: 'ACT 11: STRESS TEST', actNumber: 11, speaker: 'All', component: 'Slide53', speakerNotes: 'The thesis survives. IPS strengths are real but insufficient. Not fragile today — fragile to the specific dynamics emerging. Time to act but not unlimited. The NICET moat is real. The operating model must change. The order is buyout first then pivot then build.', source: 'Synthesis of all internal and external analysis · Counter-argument stress test' },
  { id: 54, title: 'What These Markets Reward', act: 'ACT 1: THE PLAYING FIELD', actNumber: 1, speaker: 'AJ McKean', component: 'Slide54', speakerNotes: 'Fire rewards depth and stickiness — NICET IV, AHJ relationships, multi-state licensing, code-mandated inspection, proprietary switching costs. Security rewards breadth and delivery model — open architecture, cloud capability, cyber competency, integrated solutions. Both reward recurring revenue. Both constrained by labor.', source: 'Genetec State of Physical Security 2026 · PitchBook · Team PESTEL Workbook' },
  { id: 55, title: 'The Forces Acting on Both Industries', act: 'ACT 1: THE PLAYING FIELD', actNumber: 1, speaker: 'AJ McKean', component: 'Slide55', speakerNotes: 'Five forces hitting both industries simultaneously: code evolution extending into IT territory, technology convergence raising the skill floor, capital-driven consolidation at record pace, manufacturer disruption eroding exclusivity, and the cloud/XaaS shift making subscription the expected model.', source: 'NFPA 72-2025 · Capstone Partners Feb 2026 · PitchBook · Team PESTEL Workbook' },
  { id: 56, title: 'Where Growth Is Concentrated', act: 'ACT 2: THE CONVERGENCE SQUEEZE', actNumber: 2, speaker: 'Ryan Eger', component: 'Slide56', speakerNotes: 'Ohio — Columbus #3 data center market, Meta Prometheus 1GW+. Tennessee — Nashville top metro for job growth, HCA anchors healthcare. Southeast — Atlanta, Charlotte, Florida sustained construction. Federal funding exceeding $1.3B across HSGP, school safety, and BSC Act.', source: 'PESTEL research · Congress.gov · FEMA.gov · ConstructConnect' },
  { id: 57, title: 'The Recurring Revenue Imperative', act: 'ACT 3: WHERE IPS STANDS', actNumber: 3, speaker: 'Zahria Tucker', component: 'Slide57', speakerNotes: 'IPS true recurring revenue 7-10% vs 25%+ benchmark — the single largest gap. Service margins 2.5x project margins. PE platforms at 13-14x EBITDA driven by RMR. APi Group model: every $1 inspection generates $3-4 annual service revenue. Platforms exist — Brivo, Genetec deployed. Gap is go-to-market execution.', source: 'Genetec 2026 · Grand View Research · PitchBook · APi Group 10-K · IPS Leadership' },
  { id: 58, title: 'PE in Fire Protection', act: 'ACT 2: THE CONVERGENCE SQUEEZE', actNumber: 2, speaker: 'Ryan Eger', component: 'Slide58', speakerNotes: 'Fire was the last industry to consolidate because of NICET IV barriers, AHJ relationships, and code complexity. PE is now inside. Pye-Barker doing 57 acquisitions per year in IPS geography. Carlyle/Sciens expanding eastward. Lone Star controls Edwards OEM — IPS primary supplier. APi Group proved the full playbook at $7.9B. Fire/life safety M&A up 66.7% YoY.', source: 'PitchBook · Capstone Partners Feb 2026 · APi Group 10-K · SDM Magazine' },
  { id: 59, title: 'PE in Electronic Security', act: 'ACT 2: THE CONVERGENCE SQUEEZE', actNumber: 2, speaker: 'Ryan Eger', component: 'Slide59', speakerNotes: 'Security was the first industry PE consolidated — low barriers, high fragmentation. 242 transactions in 2025, up 24% YoY. Leonard Green controls $3.7B through Convergint + Pye-Barker. Convergint entered Cincinnati and Nashville in 2025. Everon overlaps Columbus and Louisville. Pavion already in Cincinnati. Every IPS market now has PE-backed competition.', source: 'PitchBook · Capstone Partners Feb 2026 · SDM Top 100 (2024) · Genetec 2026' },
  { id: 60, title: 'PE in Electrical Contracting', act: 'ACT 2: THE CONVERGENCE SQUEEZE', actNumber: 2, speaker: 'Ryan Eger', component: 'Slide60', speakerNotes: 'The third front. 79 EC deals in 2024, 73% PE-driven. ArchKey is IPS $2.5M customer — hiring NICET staff now to replace subcontracted fire. Apollo State Group operates fire+security+EC in KY/IN/TN. EMCOR has hundreds of NICET staff. The playbook: buy EC, get GC relationships, build fire/security in-house, capture RMR. Three of IPS top 8 EC customers are already PE or corporate owned.', source: 'PitchBook · FMI Capital Advisors · ArchKey corporate · IES Holdings 10-Q · EMCOR SEC filings · IPS customer data' },
]

export const ACT_COLORS: Record<number, string> = {
  1: 'bg-accent/10 border-accent/30',
  2: 'bg-blue-50 border-blue-200',
  3: 'bg-emerald-50 border-emerald-200',
  4: 'bg-orange-50 border-orange-200',
  5: 'bg-purple-50 border-purple-200',
  6: 'bg-red-50 border-red-200',
  7: 'bg-indigo-50 border-indigo-200',
  8: 'bg-amber-50 border-amber-200',
  9: 'bg-rose-50 border-rose-200',
  10: 'bg-slate-50 border-slate-200',
  11: 'bg-cyan-50 border-cyan-200',
}

export const ACT_NAMES: Record<number, string> = {
  1: 'The World You Built',
  2: 'The Industry Is Converging',
  3: 'Moat & Gaps',
  4: 'The Path Forward',
  5: 'Close',
  6: 'What the Numbers Say',
  7: 'Where IPS Creates Value',
  8: 'The Geography Engine',
  9: 'What Breaks',
  10: 'What Replaces It',
  11: 'Stress Test',
}
